---
version: "2.1"
services:
  bitbns-report-analyzer:
    stdin_open: true # docker run -i
    tty: true # docker run -t
    image: ghcr.io/milindpatel63/bitbns-report-analyzer:main
    container_name: bitbnsreport
    volumes:
      - /home/user/bitbns/report:/reports
    restart: "no"
